
name: create-windows-bundle
on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    mk-windows-bundle:
        runs-on: windows-2022
        steps:
            - uses: actions/checkout@v3
            - run: cmd /c "windowsBundle.bat"
            - uses: actions/upload-artifact@v3
              with:
                path: ${{github.workspace}}\TryLean4Bundle.exe

