name: create-win-bundle
on:
  workflow_dispatch

jobs:
  mk-win-bundle:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Sources
        run: |
          Get-Content .env | foreach {
            $name, $value = $_.split('=')
            if ([string]::IsNullOrWhiteSpace($name) || $name.Contains('#')) { continue }
            Set-Content env:\$name $value
          }
          mkdir TryLean4Bundle
          cd TryLean4Bundle
          C:\Windows\System32\curl.exe -L -C - --output "lean-toolchain" $MATHLIB_LEAN_TOOLCHAIN_URL
          C:\Windows\System32\curl.exe -L -C - --output "z7z.exe" $Z7Z_URL
          C:\Windows\System32\curl.exe -L -C - --output "git-install.exe" $GIT_URL
          C:\Windows\System32\curl.exe -L -C - --output "vc_redist.x64.exe" $VC_REDIST_URL
          C:\Windows\System32\curl.exe -L -C - --output "elan-init.sh" $ELAN_INSTALLER_URL
          C:\Windows\System32\curl.exe -L -C - --output "vscodium.zip" $VSCODIUM_URL
          C:\Windows\System32\curl.exe -L -C - --output "lean4ext.zip" $VSCODE_LEAN4_EXT_URL

      - name: Expand Git and Intall Lean4 VSCode Extension + Tomiko PDF Reader
        run: |
          cd TryLean4Bundle
          z7z.exe x "git-install.exe" -o".\PortableGit"
          cmd /c "VSCodium\bin\codium.cmd --install-extension leanprover.lean4"
          cmd /c "VSCodium\bin\codium.cmd --install-extension tomoki1207.pdf"
        
      - name: Install Elan
        run: |
          $LEAN_TOOLCHAIN_VERSION = Get-Content lean-toolchain -Raw
          ".\PortableGit\bin\bash.exe" -c "./elan-init.sh -y --no-modify-path --default-toolchain $LEAN_TOOLCHAIN_VERSION"

      - name: Create DemoProject
        run: |
          mkdir DemoProj
          


  validate-win-bundle:
    runs-on: windows-latest

  release-win-bundle:
    runs-on: windows-latest