
name: validate-windows-bundle
on:
    workflow_dispatch:

jobs:
    validate_bundle:
        env:  
          GH_TOKEN: ${{ github.token }}
        runs-on: windows-2022
        steps:
            - name: Download-Bundle
              run: gh release download --pattern "TryLean4Bundle*.exe" --output "TryLean4Bundle.exe"

            - name: Unpack Bundle
              run: TryLean4Bundle.exe -y -o"TryLeanUnpacked"

            - name: Check Versions
              run: cmd /c "dir"

